$(document).ready(function() {
    $('select').change( function() {
        if ($('option:selected').val() == "male") {
            $('#cal').html('<iframe src="https://calendar.google.com/calendar/b/2/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;showTitle=0&amp;showNav=0&amp;showDate=1&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0&amp;src=bmFnaTd1czk4MG5ncW83MzV2ajM3MmJxcm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23009688" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>');
        } else if ($('option:selected').val() == "female") {
            $('#cal').html('<iframe src="https://calendar.google.com/calendar/b/2/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;showTitle=0&amp;showNav=0&amp;showDate=1&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0&amp;src=dmpiZnRmbm03ajNnbWEwc2hsYnRudHIwMHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23F4511E" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>');
        } else if ($('option:selected').val() == "family") {
            $('#cal').html('<iframe src="https://calendar.google.com/calendar/b/2/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;showTitle=0&amp;showNav=0&amp;showDate=1&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0&amp;src=aXFqb2cydmhqcjB0ajZsbXRhZzgxNWFoNzRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%234285F4" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>');
        } else if ($('option:selected').val() == "snap") {
            $('#cal').html('<iframe src="https://calendar.google.com/calendar/b/2/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=b2V0ZHJiczRvMDRnY3YzODRwMmJpcjVkN3NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23E67C73&amp;showTitle=0&amp;showNav=0&amp;showDate=0&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>');
        } else if ($('option:selected').val() == "pfb") {
            $('#cal').html('<iframe src="https://calendar.google.com/calendar/b/2/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;showTitle=0&amp;showNav=0&amp;showDate=1&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0&amp;src=MXQwMWo1NnM5djQyY3NjbDBqZG5laWtkaXNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23D81B60" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>');
        } else if ($('option:selected').val() == "fmnp") {
            $('#cal').html('<iframe src="https://calendar.google.com/calendar/b/2/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=b2V0ZHJiczRvMDRnY3YzODRwMmJpcjVkN3NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23E67C73&amp;showTitle=0&amp;showNav=0&amp;showDate=0&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>');
        } else {
            $('#cal').html('<iframe src="https://calendar.google.com/calendar/b/2/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;showTitle=0&amp;showNav=0&amp;showDate=1&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0&amp;src=aXFqb2cydmhqcjB0ajZsbXRhZzgxNWFoNzRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=dmpiZnRmbm03ajNnbWEwc2hsYnRudHIwMHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=bmtjZG40OG91bGp1c2NmYzJldXZlNDlsbHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=bmFnaTd1czk4MG5ncW83MzV2ajM3MmJxcm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=MXQwMWo1NnM5djQyY3NjbDBqZG5laWtkaXNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=b2V0ZHJiczRvMDRnY3YzODRwMmJpcjVkN3NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%234285F4&amp;color=%23F4511E&amp;color=%238E24AA&amp;color=%23009688&amp;color=%23D81B60&amp;color=%23E67C73" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>');
        }
    });
});